### ISSUE TITLE
Area of a circle?

### ISSUE THREAD

**Issue by Paraka321** [jdhitsolutions/MyNumber#2]
The area of a circle method is potentially misleading. I, personally, expect my-number to represent the diameter of a circle, rather than the radius. I don't expect the area of a circle to be larger than a square, given that diameter equals one side of the square. This puts it more in line with my-number.square() in terms of logic.

Rather than changing it and only representing one, I feel like it would be beneficial to include both. Perhaps something like CircleAreaR and CircleAreaD or any other way of labeling the difference between the two methods. Or any clarification in the help. Or as a comment in the code.

**Comment by jdhitsolutions** [comment]
Let me take a look. Thanks for the feedback.

**Comment by jdhitsolutions** [comment]
The circlearea formula is pi * r^2 which seems pretty straightforward to me. I think I'm just going to update the documentation.
